name: Owasp Zap Scan DAST
on: [push]
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
        - name: ZAP Scan
          uses: zaproxy/action-full-scan@v0.9.0
          with:
            target: 'https://www.zaproxy.org/'